### 
POST http://localhost:3000/admin

### 
POST http://localhost:3000/login
Content-Type: application/json

{
  "email": "alvaro.vazquez.1716@gmail.com",
  "password": "SecurePass@123"
}

### 
GET http://localhost:3000/admin/roadmaps
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Im96WHRwekJtZ0FDc0xNcjlqY281IiwiZW1haWwiOiJhbHZhcm8udmF6cXVlei4xNzE2QGdtYWlsLmNvbSIsInJvbGUiOiJBRE1JTiIsImlhdCI6MTczOTQ2NDIxNCwiZXhwIjoxNzM5NTUwNjE0fQ.TWEXgGx_RaYFEQupAVSA-6oZsY1EZc5XxH259rED2bo

### 
GET http://localhost:3000/admin/roadmaps/label/data-analyst
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Im96WHRwekJtZ0FDc0xNcjlqY281IiwiZW1haWwiOiJhbHZhcm8udmF6cXVlei4xNzE2QGdtYWlsLmNvbSIsInJvbGUiOiJBRE1JTiIsImlhdCI6MTczOTQ2NDIxNCwiZXhwIjoxNzM5NTUwNjE0fQ.TWEXgGx_RaYFEQupAVSA-6oZsY1EZc5XxH259rED2bo

### 
GET http://localhost:3000/admin/roadmaps/year/2025
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Im96WHRwekJtZ0FDc0xNcjlqY281IiwiZW1haWwiOiJhbHZhcm8udmF6cXVlei4xNzE2QGdtYWlsLmNvbSIsInJvbGUiOiJBRE1JTiIsImlhdCI6MTczOTQ2NDIxNCwiZXhwIjoxNzM5NTUwNjE0fQ.TWEXgGx_RaYFEQupAVSA-6oZsY1EZc5XxH259rED2bo

### 
GET http://localhost:3000/admin/roadmaps/mention/blockchain-engineer
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Im96WHRwekJtZ0FDc0xNcjlqY281IiwiZW1haWwiOiJhbHZhcm8udmF6cXVlei4xNzE2QGdtYWlsLmNvbSIsInJvbGUiOiJBRE1JTiIsImlhdCI6MTczOTQ2NDIxNCwiZXhwIjoxNzM5NTUwNjE0fQ.TWEXgGx_RaYFEQupAVSA-6oZsY1EZc5XxH259rED2bo

### 
POST http://localhost:3000/roadmaps/many
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Im96WHRwekJtZ0FDc0xNcjlqY281IiwiZW1haWwiOiJhbHZhcm8udmF6cXVlei4xNzE2QGdtYWlsLmNvbSIsInJvbGUiOiJBRE1JTiIsImlhdCI6MTczOTQ2NDIxNCwiZXhwIjoxNzM5NTUwNjE0fQ.TWEXgGx_RaYFEQupAVSA-6oZsY1EZc5XxH259rED2bo

[
  {
    "name": "data scientist",
    "metion": "Ingenieria de datos",
    "description": "data scientist roadmap",
    "label": ["data analyst"],
    "year": 3,
    "recommendedLabels": ["ai engineer"," blockchain engineer"],
    "link": "https://roadmap.sh/data-scientist"
  },
  {
    "name": "data scientist",
    "metion": "Ingenieria de datos",
    "description": "data scientist roadmap",
    "label": ["data analyst"],
    "year": 3,
    "recommendedLabels": ["ai engineer"," blockchain engineer"],
    "link": "https://roadmap.sh/data-scientist"
  },
  {
    "name": "frontend beginner developer",
    "metion": "",
    "description": "frontend beginner developer roadmap",
    "label": ["frontend beginner developer"],
    "year": 1,
    "recommendedLabels": ["frontend developer","fullstack developer"],
    "link": "https://roadmap.sh/frontend?r=frontend-beginner"
  },
  {
    "name": "backend beginner developer",
    "metion": "",
    "description": "backend  beginner developer roadmap",
    "label": ["backend beginner developer"],
    "year": 1,
    "recommendedLabels": ["fullstack developer"],
    "link": "https://roadmap.sh/backend?r=backend-beginner"
  },
  {
    "name": "frontend developer",
    "metion": "",
    "description": "frontend developer roadmap",
    "label": ["frontend developer"],
    "year": 1,
    "recommendedLabels": ["backend beginner developer","backend developer","fullstack developer"] ,
    "link": "https://roadmap.sh/frontend"
  },
  {
    "name": "backend developer",
    "metion": "",
    "year": 1,
    "description": "backend developer roadmap",
    "label": ["backend developer"],
    "recommendedLabels": ["frontend  beginner developer","frontend developer","fullstack developer"],
    "link": "https://roadmap.sh/backend"
  },
  {
    "name": "fullstack developer",
    "metion": "",
    "description": "fullstack developer roadmap",
    "label": ["fullstack developer"],
    "year": 2,
    "recommendedLabels": ["ai","blockchain"],
    "link": "https://roadmap.sh/fullstack"
  },
  {
    "name": "devops",
    "metion": "",
    "description": "devops roadmap",
    "label": ["devops"],
    "year": 3,
    "recommendedLabels": ["ai ","blockchain"],
    "link": "https://roadmap.sh/devops"
  },
  {
    "name": "ai engineer",
    "metion": "Ingenieria de datos",
    "description": "ai engineer roadmap",
    "label": ["ai","ia","artificial intelligence","inteligencia artificial"],
    "year": 3,
    "recommendedLabels": ["ai","blockchain"],
    "link": "https://roadmap.sh/ai"
  },
  {
    "name": "blockchain",
    "metion": "Ingenieria de datos",
    "description": "blockchain engineer roadmap",
    "label": ["blockchain"],
    "year": 3,
    "recommendedLabels": ["ai","blockchain"],
    "link": "https://roadmap.sh/blockchain"
  },
  {
    "name": "cybersecurity",
    "metion": "Ciberseguridad",
    "description": "cybersecurity engineer roadmap",
    "label": ["cybersecurity"],
    "year": 3,
    "recommendedLabels": ["ai","blockchain"],
    "link": "https://roadmap.sh/cybersecurity"
  },
  {
    "name": "software arquiteture",
    "metion": "ciberseguridad",
    "description": "software arquiteture roadmap",
    "label": ["software arquiteture"],
    "year": 3,
    "recommendedLabels": ["ai","blockchain"],
    "link": "https://roadmap.sh/ cloud"
  },
  {
    "name": "game developer",
    "metion": "Programacion grafica",
    "description": "game developer roadmap",
    "label": ["game developer"],
    "year": 3,
    "recommendedLabels": ["devrel"],
    "link": "https://roadmap.sh/game-developer"
  },
  {
    "name": "android developer",
    "metion": "",
    "description": "android developer roadmap",
    "label": ["android developer"],
    "year": 3,
    "recommendedLabels": ["ios developer"],
    "link": "https://roadmap.sh/android"
  },
  {
    "name": "ios developer",
    "metion": "",
    "description": "ios developer roadmap",
    "label": ["ios developer"],
    "year": 3,
    "recommendedLabels": ["android developer"],
    "link": "https://roadmap.sh/ios"
  },
  {
    "name": "react developer",
    "metion": "Ingenieria de datos",
    "description": "react developer roadmap",
    "label": ["react developer"],
    "year": 3,
    "recommendedLabels": ["ai","blockchain"],
    "link": "https://roadmap.sh/react"
  },
  {
    "name": "client game developer",
    "metion": "programacion Grafica",
    "description": "client game developer roadmap",
    "label": ["client game developer"],
    "year": 3,
    "recommendedLabels": ["server game developer"],
    "link": "https://roadmap.sh/game-developer"
  },
  {
    "name": "server game developer",
    "metion": "programacion Grafica",
    "description": "server  gamedeveloper roadmap",
    "label": ["client game developer"],
    "year": 3,
    "recommendedLabels": ["server game developer"],
    "link": "https://roadmap.sh/game-developer"
  },
  {
    "name": "react developer",
    "metion": "",
    "description": "react developer roadmap",
    "label": ["react developer"],
    "year": 3,
    "recommendedLabels": ["frontend developer","fullstack developer"],
    "link": "https://roadmap.sh/react"
  }  
]

###
PATCH http://localhost:3000/admin/roadmaps/roadmapId
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Im96WHRwekJtZ0FDc0xNcjlqY281IiwiZW1haWwiOiJhbHZhcm8udmF6cXVlei4xNzE2QGdtYWlsLmNvbSIsInJvbGUiOiJBRE1JTiIsImlhdCI6MTczOTQ2NDIxNCwiZXhwIjoxNzM5NTUwNjE0fQ.TWEXgGx_RaYFEQupAVSA-6oZsY1EZc5XxH259rED2bo

{
    "description": "Updated AI Engineer roadmap",
    "year": 2026
}

### Delete a roadmap (Admin Only)
DELETE http://localhost:3000/admin/roadmaps/roadmapId
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Im96WHRwekJtZ0FDc0xNcjlqY281IiwiZW1haWwiOiJhbHZhcm8udmF6cXVlei4xNzE2QGdtYWlsLmNvbSIsInJvbGUiOiJBRE1JTiIsImlhdCI6MTczOTQ2NDIxNCwiZXhwIjoxNzM5NTUwNjE0fQ.TWEXgGx_RaYFEQupAVSA-6oZsY1EZc5XxH259rED2bo
