### Register User
POST http://localhost:3000/register
Content-Type: application/json

{
  "email": "alvaro.vazquez@live.u-tad.com",
  "password": "SecurePass123!",
  "seedWord": "diegoenjoyer"
}

### Login User
POST http://localhost:3000/login
Content-Type: application/json

{
  "email": "alvaro.vazquez@live.u-tad.com",
  "password": "SecurePass@123"
}

### Login User
POST https://backend-production-b78c.up.railway.app/login
Content-Type: application/json

{
  "email": "alvaro.vazquez@live.u-tad.com",
  "password": "SecurePass@123"
}

### Update password
PUT http://localhost:3000/updatePassword
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IlY3dmxMb0pnQWtkbzRLZ1NHa1Y1IiwiZW1haWwiOiJhbHZhcm8udmF6cXVlekBsaXZlLnUtdGFkLmNvbSIsInJvbGUiOiJTVFVERU5UIiwiaWF0IjoxNzM4ODYzNTkxLCJleHAiOjE3Mzg5NDk5OTF9.tGUKnTNxlTq7QguYwcRhTPimGhZYZTirSLsgg5Hochc

{
  "email": "alvaro.vazquez@live.u-tad.com",
  "newPassword": "SecurePass@123",
  "seedWord": "diego"
}

### Logout User
POST http://localhost:3000/logout
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IlY3dmxMb0pnQWtkbzRLZ1NHa1Y1IiwiZW1haWwiOiJhbHZhcm8udmF6cXVlekBsaXZlLnUtdGFkLmNvbSIsInJvbGUiOiJTVFVERU5UIiwiaWF0IjoxNzM4ODYzNTkxLCJleHAiOjE3Mzg5NDk5OTF9.tGUKnTNxlTq7QguYwcRhTPimGhZYZTirSLsgg5Hochc

###
GET http://localhost:3000/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IlY3dmxMb0pnQWtkbzRLZ1NHa1Y1IiwiZW1haWwiOiJhbHZhcm8udmF6cXVlekBsaXZlLnUtdGFkLmNvbSIsInJvbGUiOiJTVFVERU5UIiwiaWF0IjoxNzM5MDM0NDI0LCJleHAiOjE3MzkxMjA4MjR9.ibPzuaKuKqNK26JZ0x5ehMbZ2tCUkKxeSUVQzMFqqJE

### 
GET https://backend-production-b78c.up.railway.app/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IlY3dmxMb0pnQWtkbzRLZ1NHa1Y1IiwiZW1haWwiOiJhbHZhcm8udmF6cXVlekBsaXZlLnUtdGFkLmNvbSIsInJvbGUiOiJTVFVERU5UIiwiaWF0IjoxNzM5MDU0NzY2LCJleHAiOjE3MzkxNDExNjZ9.UsdWM7RuGCQR9AQeQXIv7bsXvrsGvSsRtEorz9zIE0Q

###
PATCH http://localhost:3000/
Content-Type: application/json
Authorization : Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IlY3dmxMb0pnQWtkbzRLZ1NHa1Y1IiwiZW1haWwiOiJhbHZhcm8udmF6cXVlekBsaXZlLnUtdGFkLmNvbSIsInJvbGUiOiJTVFVERU5UIiwiaWF0IjoxNzM5MDI5NDc2LCJleHAiOjE3MzkxMTU4NzZ9.vjvjdDp78U6XTmDKmmQnxeUXX3iVQ4m_sGeucwL8UwM

{
  "seedWord": "diego"
}

###
PATCH http://localhost:3000/metadata
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IlY3dmxMb0pnQWtkbzRLZ1NHa1Y1IiwiZW1haWwiOiJhbHZhcm8udmF6cXVlekBsaXZlLnUtdGFkLmNvbSIsInJvbGUiOiJTVFVERU5UIiwiaWF0IjoxNzM5MDM0NDI0LCJleHAiOjE3MzkxMjA4MjR9.ibPzuaKuKqNK26JZ0x5ehMbZ2tCUkKxeSUVQzMFqqJE

{
  "languages": [
    { "language": "English", "level": "medium" },    
    { "language": "French", "level": "low" }
  ]
}

### Update Metadata (Modify Specialization)
PATCH http://localhost:3000/metadata
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IlY3dmxMb0pnQWtkbzRLZ1NHa1Y1IiwiZW1haWwiOiJhbHZhcm8udmF6cXVlekBsaXZlLnUtdGFkLmNvbSIsInJvbGUiOiJTVFVERU5UIiwiaWF0IjoxNzM5MDM0NDI0LCJleHAiOjE3MzkxMjA4MjR9.ibPzuaKuKqNK26JZ0x5ehMbZ2tCUkKxeSUVQzMFqqJE

{
  "specialization": "Artificial Intelligence"
}

### Update Metadata (Invalid Field)
PATCH http://localhost:3000/metadata
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IlY3dmxMb0pnQWtkbzRLZ1NHa1Y1IiwiZW1haWwiOiJhbHZhcm8udmF6cXVlekBsaXZlLnUtdGFkLmNvbSIsInJvbGUiOiJTVFVERU5UIiwiaWF0IjoxNzM5MDM0NDI0LCJleHAiOjE3MzkxMjA4MjR9.ibPzuaKuKqNK26JZ0x5ehMbZ2tCUkKxeSUVQzMFqqJE

{
  "invalidField": "SomeData"
}

### Delete Metadata (Remove a Language)
DELETE http://localhost:3000/metadata
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IlY3dmxMb0pnQWtkbzRLZ1NHa1Y1IiwiZW1haWwiOiJhbHZhcm8udmF6cXVlekBsaXZlLnUtdGFkLmNvbSIsInJvbGUiOiJTVFVERU5UIiwiaWF0IjoxNzM5MDM0NDI0LCJleHAiOjE3MzkxMjA4MjR9.ibPzuaKuKqNK26JZ0x5ehMbZ2tCUkKxeSUVQzMFqqJE

{
  "languages": [
    { "language": "French", "level": "low" }
  ]
}

### Delete Metadata (Remove Specialization)
DELETE http://localhost:3000/metadata
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IlY3dmxMb0pnQWtkbzRLZ1NHa1Y1IiwiZW1haWwiOiJhbHZhcm8udmF6cXVlekBsaXZlLnUtdGFkLmNvbSIsInJvbGUiOiJTVFVERU5UIiwiaWF0IjoxNzM5MDM0NDI0LCJleHAiOjE3MzkxMjA4MjR9.ibPzuaKuKqNK26JZ0x5ehMbZ2tCUkKxeSUVQzMFqqJE

{
  "specialization" : ""
}

### Delete Metadata (Invalid Field)
DELETE http://localhost:3000/metadata
Content-Type: application/json
Authorization: Bearer YOUR_JWT_TOKEN_HERE

{
  "randomField": "ShouldFail"
}


