### 
POST http://localhost:3000/setup/admin
Content-Type: application/json

### 
POST http://localhost:3000/login
Content-Type: application/json

{
  "email": "admin@example.com",
  "password": "AdminPass123"
}

### 
POST http://localhost:3000/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjZrR1RENVhqbXVqd2o0c2tpREx4Iiwicm9sZSI6IkFETUlOIiwiaWF0IjoxNzM4NDQ3MTc1LCJleHAiOjE3Mzg1MzM1NzV9.a9yBOIY7E2SVJS-h5HAg8HAphL3jOm6fwE6dzuYyoG4
Content-Type: application/json

{
  "name": "John Doe",
  "email": "johndoe@example.com",
  "password": "SecurePass123",
  "role": "STUDENT",
  "metadata": {
    "academicHistory": {
      "Mathematics": 8.5,
      "Physics": 7.8,
      "Computer Science": 9.2
    },
    "profileCompleted": true,
    "preferences": {
      "careerInterest": "Software Engineering",
      "studyHabits": "Morning",
      "extracurriculars": ["Coding Club", "Robotics Team"]
    },
    "certifications": [
      {
        "name": "Machine Learning",
        "issuedBy": "Coursera",
        "date": "2023-05-15"
      },
      {
        "name": "Cyber Security",
        "issuedBy": "Udemy",
        "date": "2024-01-20"
      }
    ],
    "experience": [
      {
        "company": "Tech Startups Inc.",
        "position": "Intern",
        "duration": "3 months",
        "skillsGained": ["Python", "Data Analysis"]
      }
    ]
  }
}


