### register 
POST http://localhost:3000/register
Content-Type: application/json

{
  "email": "alvaroVqz@live.u-tad.com",
  "password": "SecurePass123!",
  "seedWord": "sash"
}

### login con railway
POST https://backend-production-94e4.up.railway.app/login
Content-Type: application/json

{
  "email": "alvaroVqz@live.u-tad.com",
  "password": "SecurePass123!"
}

### login
POST http://localhost:3000/login
Content-Type: application/json

{
  "email": "alvaroVqz@live.u-tad.com",
  "password": "SecurePass123!"
}

###
PATCH http://localhost:3000/metadata
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Ijl1ZUhRdUhNOFVBRU0wUWV5QjB6IiwiZW1haWwiOiJhbHZhcm9WcXpAbGl2ZS51LXRhZC5jb20iLCJyb2xlIjoiU1RVREVOVCIsImlhdCI6MTc0MDQ3NTUxMSwiZXhwIjoxNzQwNTYxOTExfQ.u1Lvc7er9v9mGbDKcjoxJXtsSdQpQwola67vQC5SCZ8

{
    "firstName": "Alvaro",
    "lastName": "Vazquez",
    "gender": "male",
    "dni": "12345678A",
    "degree": "INSO_DATA",
    "specialization": "Data Analyst",
    "institution": "U-Tad",
    "birthDate": "1985-08-20",
    "endDate": "2026-06-30",
    "languages": [
        { "language": "English", "level": "high" },
        { "language": "Spanish", "level": "high" },
        { "language": "French", "level": "high" }
    ],
    "skills": [
        { "skill": "C" }
    ],
    "certifications": [
        { "name": "AWS Certified Developer", "date": "2024-01-15", "institution": "Amazon" },
        { "name": "Microsoft Certified: Azure Developer Associate", "date": "2024-02-15", "institution": "Microsoft" },
        { "name": "Google Professional Data Engineer", "date": "2024-03-15", "institution": "Google" },
        { "name": "Oracle Certified Professional: Java SE 11 Developer", "date": "2024-04-15", "institution": "Oracle" }
    ],
    "workExperience": [
        { 
            "jobType": "Intern", 
            "startDate": "2023-06-01", 
            "endDate": "2023-12-31", 
            "company": "Nvidia", 
            "description": "AI Developer", 
            "responsibilities": "AI development tasks" 
        }
    ]
}

###
PATCH http://localhost:3000/metadata
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Ijl1ZUhRdUhNOFVBRU0wUWV5QjB6IiwiZW1haWwiOiJhbHZhcm9WcXpAbGl2ZS51LXRhZC5jb20iLCJyb2xlIjoiU1RVREVOVCIsImlhdCI6MTc0MDMzMzE5MywiZXhwIjoxNzQwNDE5NTkzfQ.0MiE0N2W7xdad3g86_RXOb0HVdBtDlmKwexcpm4VD1Q

{
    "firstName": "Alvaroo",
    "lastName": "Vazquezz"
}

### 
PATCH http://localhost:3000/metadata
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Ijl1ZUhRdUhNOFVBRU0wUWV5QjB6IiwiZW1haWwiOiJhbHZhcm9WcXpAbGl2ZS51LXRhZC5jb20iLCJyb2xlIjoiU1RVREVOVCIsImlhdCI6MTc0MDMzMzE5MywiZXhwIjoxNzQwNDE5NTkzfQ.0MiE0N2W7xdad3g86_RXOb0HVdBtDlmKwexcpm4VD1Q

{
    "skills": [
        { "skill": "C++" },
        { "skill": "Python" },
        { "skill": "Rust" }
    ]
}

###
PATCH http://localhost:3000/metadata
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Ijl1ZUhRdUhNOFVBRU0wUWV5QjB6IiwiZW1haWwiOiJhbHZhcm9WcXpAbGl2ZS51LXRhZC5jb20iLCJyb2xlIjoiU1RVREVOVCIsImlhdCI6MTc0MDMzMzE5MywiZXhwIjoxNzQwNDE5NTkzfQ.0MiE0N2W7xdad3g86_RXOb0HVdBtDlmKwexcpm4VD1Q

{
    "certifications": [
        { "name": "AWS Certified Developer", "date": "2024-01-15", "institution": "Amazon" },
        { "name": "Microsoft Certified: Azure Developer Associate", "date": "2024-02-15", "institution": "Microsoft" },
        { "name": "Google Professional Data Engineer", "date": "2024-03-15", "institution": "Google" },
        { "name": "Oracle Certified Professional: Java SE 11 Developer", "date": "2024-04-15", "institution": "Oracle" },
        { "name": "TensorFlow Developer Certificate", "date": "2025-01-10", "institution": "Google" }
    ]
}

### 
PATCH http://localhost:3000/metadata
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Ijl1ZUhRdUhNOFVBRU0wUWV5QjB6IiwiZW1haWwiOiJhbHZhcm9WcXpAbGl2ZS51LXRhZC5jb20iLCJyb2xlIjoiU1RVREVOVCIsImlhdCI6MTc0MDMzMzE5MywiZXhwIjoxNzQwNDE5NTkzfQ.0MiE0N2W7xdad3g86_RXOb0HVdBtDlmKwexcpm4VD1Q

{
    "workExperience": [
        { 
            "jobType": "Intern", 
            "startDate": "2023-06-01", 
            "endDate": "2023-12-31", 
            "company": "Nvidia", 
            "description": "AI Developer", 
            "responsibilities": "AI development tasks" 
        },
        { 
            "jobType": "Software Engineer", 
            "startDate": "2024-02-01", 
            "endDate": "2024-12-31", 
            "company": "Google", 
            "description": "Backend Developer", 
            "responsibilities": "Developing scalable backend systems" 
        }
    ]
}

###
PATCH http://localhost:3000/metadata
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Ijl1ZUhRdUhNOFVBRU0wUWV5QjB6IiwiZW1haWwiOiJhbHZhcm9WcXpAbGl2ZS51LXRhZC5jb20iLCJyb2xlIjoiU1RVREVOVCIsImlhdCI6MTc0MDMzMzE5MywiZXhwIjoxNzQwNDE5NTkzfQ.0MiE0N2W7xdad3g86_RXOb0HVdBtDlmKwexcpm4VD1Q

{
    "languages": [
        { "language": "English", "level": "high" },
        { "language": "Spanish", "level": "high" },
        { "language": "German", "level": "medium" }
    ]
}

###
PATCH http://localhost:3000/metadata
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Ijl1ZUhRdUhNOFVBRU0wUWV5QjB6IiwiZW1haWwiOiJhbHZhcm9WcXpAbGl2ZS51LXRhZC5jb20iLCJyb2xlIjoiU1RVREVOVCIsImlhdCI6MTc0MDMzMzE5MywiZXhwIjoxNzQwNDE5NTkzfQ.0MiE0N2W7xdad3g86_RXOb0HVdBtDlmKwexcpm4VD1Q

{
    "institution": "MIT"
}

### Test para obtener un estudiante
GET http://localhost:3000/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Ijl1ZUhRdUhNOFVBRU0wUWV5QjB6IiwiZW1haWwiOiJhbHZhcm9WcXpAbGl2ZS51LXRhZC5jb20iLCJyb2xlIjoiU1RVREVOVCIsImlhdCI6MTc0MDMzMzE5MywiZXhwIjoxNzQwNDE5NTkzfQ.0MiE0N2W7xdad3g86_RXOb0HVdBtDlmKwexcpm4VD1Q

### Test para obtener la metadata de un estudiante
GET http://localhost:3000/metadata
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Ijl1ZUhRdUhNOFVBRU0wUWV5QjB6IiwiZW1haWwiOiJhbHZhcm9WcXpAbGl2ZS51LXRhZC5jb20iLCJyb2xlIjoiU1RVREVOVCIsImlhdCI6MTc0MDMzNjUzNywiZXhwIjoxNzQwNDIyOTM3fQ.KA9niP2a_j7MaiFt-WazXC5_NK2iBRUVX8qAJ9zJ-_4

###  Test para eliminar algun dato la metadata de un estudiante
DELETE http://localhost:3000/metadata
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Ijl1ZUhRdUhNOFVBRU0wUWV5QjB6IiwiZW1haWwiOiJhbHZhcm9WcXpAbGl2ZS51LXRhZC5jb20iLCJyb2xlIjoiU1RVREVOVCIsImlhdCI6MTc0MDMzMzE5MywiZXhwIjoxNzQwNDE5NTkzfQ.0MiE0N2W7xdad3g86_RXOb0HVdBtDlmKwexcpm4VD1Q

{
    "workExperience": [
        { "jobType": "Intern", "startDate": "2023-06-01", "endDate": "2023-12-31", "company": "Nvidia", "description": "AI Developer", "responsibilities": "AI development tasks" }
    ],
    "certifications": [
        { "name": "AWS Certified Developer", "date": "2024-01-15", "institution": "Amazon" },
        { "name": "Microsoft Certified: Azure Developer Associate", "date": "2024-02-15", "institution": "Microsoft" },
        { "name": "Oracle Certified Professional: Java SE 11 Developer", "date": "2024-04-15", "institution": "Oracle" }
    ]
}

### Test obtener el historial academico de un estudiante
GET http://localhost:3000/AH
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Ijl1ZUhRdUhNOFVBRU0wUWV5QjB6IiwiZW1haWwiOiJhbHZhcm9WcXpAbGl2ZS51LXRhZC5jb20iLCJyb2xlIjoiU1RVREVOVCIsImlhdCI6MTc0MDMzMzE5MywiZXhwIjoxNzQwNDE5NTkzfQ.0MiE0N2W7xdad3g86_RXOb0HVdBtDlmKwexcpm4VD1Q

### subir notas de un estudiante
PATCH http://localhost:3000/AH
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Ijl1ZUhRdUhNOFVBRU0wUWV5QjB6IiwiZW1haWwiOiJhbHZhcm9WcXpAbGl2ZS51LXRhZC5jb20iLCJyb2xlIjoiU1RVREVOVCIsImlhdCI6MTc0MDMzMzE5MywiZXhwIjoxNzQwNDE5NTkzfQ.0MiE0N2W7xdad3g86_RXOb0HVdBtDlmKwexcpm4VD1Q

{
  "grades": [
    { "name": "Fundamentos de Desarrollo Web", "grade": 8.5 },
    { "name": "Bases de Datos", "grade": 8.5 },
    { "name": "Álgebra", "grade": 6.8 }
  ]
}

### optener a los profesores
GET http://localhost:3000/teacher
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Ijl1ZUhRdUhNOFVBRU0wUWV5QjB6IiwiZW1haWwiOiJhbHZhcm9WcXpAbGl2ZS51LXRhZC5jb20iLCJyb2xlIjoiU1RVREVOVCIsImlhdCI6MTc0MDQ4ODQxMSwiZXhwIjoxNzQwNTc0ODExfQ.zfCPJclJBqcJ2XnkwEiZB-qzN3mqx6dmYC85RH6KFF0

### Un estudiante agrega a un profesor
POST http://localhost:3000/student/teacher
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Ijl1ZUhRdUhNOFVBRU0wUWV5QjB6IiwiZW1haWwiOiJhbHZhcm9WcXpAbGl2ZS51LXRhZC5jb20iLCJyb2xlIjoiU1RVREVOVCIsImlhdCI6MTc0MDQ4ODQxMSwiZXhwIjoxNzQwNTc0ODExfQ.zfCPJclJBqcJ2XnkwEiZB-qzN3mqx6dmYC85RH6KFF0

{
  "teacherId": "ZN1U3pNxYFEXuQ7ZZFha"
}

### Ver a todos los profesores de un estudiante
GET http://localhost:3000/student/teacher
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Ijl1ZUhRdUhNOFVBRU0wUWV5QjB6IiwiZW1haWwiOiJhbHZhcm9WcXpAbGl2ZS51LXRhZC5jb20iLCJyb2xlIjoiU1RVREVOVCIsImlhdCI6MTc0MDQ4ODQxMSwiZXhwIjoxNzQwNTc0ODExfQ.zfCPJclJBqcJ2XnkwEiZB-qzN3mqx6dmYC85RH6KFF0

### Un estudiante enviar un notification a un profesor
POST http://localhost:3000/student/teacher/notification
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Ijl1ZUhRdUhNOFVBRU0wUWV5QjB6IiwiZW1haWwiOiJhbHZhcm9WcXpAbGl2ZS51LXRhZC5jb20iLCJyb2xlIjoiU1RVREVOVCIsImlhdCI6MTc0MDMzMzE5MywiZXhwIjoxNzQwNDE5NTkzfQ.0MiE0N2W7xdad3g86_RXOb0HVdBtDlmKwexcpm4VD1Q

{
  "teacherId": "ZN1U3pNxYFEXuQ7ZZFha",
  "message": "Hola, esto es un test"
}

### login teacher
POST http://localhost:3000/login
Content-Type: application/json

{
  "email": "alvaro.vazquez@u-tad.com",
  "password": "SecurePass123!"
}

###
GET http://localhost:3000/student/teacher/getAllStudents
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IlpOMVUzcE54WUZFWHVRN1paRmhhIiwiZW1haWwiOiJhbHZhcm8udmF6cXVlekB1LXRhZC5jb20iLCJyb2xlIjoiVEVBQ0hFUiIsImlhdCI6MTc0MDQ4ODU0OCwiZXhwIjoxNzQwNTc0OTQ4fQ.4o5zOfQfRt2u-E8DxdqY8DFlJPGCtRWB8O-FuejCRMQ

###
GET http://localhost:3000/student/teacher/getStudent
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IlpOMVUzcE54WUZFWHVRN1paRmhhIiwiZW1haWwiOiJhbHZhcm8udmF6cXVlekB1LXRhZC5jb20iLCJyb2xlIjoiVEVBQ0hFUiIsImlhdCI6MTc0MDQ4ODU0OCwiZXhwIjoxNzQwNTc0OTQ4fQ.4o5zOfQfRt2u-E8DxdqY8DFlJPGCtRWB8O-FuejCRMQ

{
  "studentId": "9ueHQuHM8UAEM0QeyB0z"
}

### Ver todas las notificaciones de un profesor
GET http://localhost:3000/student/teacher/notification
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IlpOMVUzcE54WUZFWHVRN1paRmhhIiwiZW1haWwiOiJhbHZhcm8udmF6cXVlekB1LXRhZC5jb20iLCJyb2xlIjoiVEVBQ0hFUiIsImlhdCI6MTc0MDI0ODkyMSwiZXhwIjoxNzQwMzM1MzIxfQ.jFU6hq_9J9SBhrU2gXCIm0l0ebfBWwQoMaqP2-EqFxM

### Un alumno se le asigna un roadmap
PATCH http://localhost:3000/userRoadmap
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Ijl1ZUhRdUhNOFVBRU0wUWV5QjB6IiwiZW1haWwiOiJhbHZhcm9WcXpAbGl2ZS51LXRhZC5jb20iLCJyb2xlIjoiU1RVREVOVCIsImlhdCI6MTc0MDQzMTUyOCwiZXhwIjoxNzQwNTE3OTI4fQ.M_31zRJXg9LDXCZIMU0AxkcFDJNbFUBfKemrjdHvyDM

### Un alumno actualiza el estado de un campo de su roadmap
PATCH http://localhost:3000/userRoadmap
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Ijl1ZUhRdUhNOFVBRU0wUWV5QjB6IiwiZW1haWwiOiJhbHZhcm9WcXpAbGl2ZS51LXRhZC5jb20iLCJyb2xlIjoiU1RVREVOVCIsImlhdCI6MTc0MDQzMTUyOCwiZXhwIjoxNzQwNTE3OTI4fQ.M_31zRJXg9LDXCZIMU0AxkcFDJNbFUBfKemrjdHvyDM
Content-Type: application/json

{
    "sectionName": "Bases de Datos",
    "topicName": "Bases de Datos NoSQL",
    "newStatus": "done"
}

### Obtener el roadmap del usuario autenticado
GET http://localhost:3000/userRoadmap
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Ijl1ZUhRdUhNOFVBRU0wUWV5QjB6IiwiZW1haWwiOiJhbHZhcm9WcXpAbGl2ZS51LXRhZC5jb20iLCJyb2xlIjoiU1RVREVOVCIsImlhdCI6MTc0MDQzMTUyOCwiZXhwIjoxNzQwNTE3OTI4fQ.M_31zRJXg9LDXCZIMU0AxkcFDJNbFUBfKemrjdHvyDM

### Eliminar el roadmap del usuario autenticado
DELETE http://localhost:3000/userRoadmap
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Ijl1ZUhRdUhNOFVBRU0wUWV5QjB6IiwiZW1haWwiOiJhbHZhcm9WcXpAbGl2ZS51LXRhZC5jb20iLCJyb2xlIjoiU1RVREVOVCIsImlhdCI6MTc0MDM0MDE2MiwiZXhwIjoxNzQwNDI2NTYyfQ.FlNEXGnVBwxFUzMDo7t2GCnnTE6b-x2__ggYlSFrIv0