###
POST http://localhost:3000/login
Content-Type: application/json

{
  "email": "alvaroVqzdelete@live.u-tad.com",
  "password": "SecurePass123!"
}

###
POST http://localhost:3000/login
Content-Type: application/json

{
  "email": "alvaroVqzdelete@u-tad.com",
  "password": "SecurePass123!"
}

### 
POST http://localhost:3000/deletionRequest
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6InZCelczU0pFUkpkMVVSY0VzS0Q2IiwiZW1haWwiOiJhbHZhcm9WcXpkZWxldGVAbGl2ZS51LXRhZC5jb20iLCJyb2xlIjoiU1RVREVOVCIsImlhdCI6MTc0MzAwODk3NiwiZXhwIjoxNzQzMDk1Mzc2fQ.2U6njRGmURHJ9MLvYygK1b9kXLfWfRk4Sza_fE8sK8o

{
  "reason": "... idk"
}

### 
POST http://localhost:3000/deletionRequest
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImRYVjZBbkd4MzUwNEVFM1cxejFCIiwiZW1haWwiOiJhbHZhcm9WcXpkZWxldGVAdS10YWQuY29tIiwicm9sZSI6IlRFQUNIRVIiLCJpYXQiOjE3NDI5MTg1NzMsImV4cCI6MTc0MzAwNDk3M30.c7GzjZKXPOjUAAyI_un6_xenw8OSj0Y9YIyzlHiMSKM

{
  "reason": "... idk"
}

### 
DELETE http://localhost:3000/deletionRequest
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6InZCelczU0pFUkpkMVVSY0VzS0Q2IiwiZW1haWwiOiJhbHZhcm9WcXpkZWxldGVAbGl2ZS51LXRhZC5jb20iLCJyb2xlIjoiU1RVREVOVCIsImlhdCI6MTc0MzAwODk3NiwiZXhwIjoxNzQzMDk1Mzc2fQ.2U6njRGmURHJ9MLvYygK1b9kXLfWfRk4Sza_fE8sK8o

### 
DELETE http://localhost:3000/deletionRequest
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImRYVjZBbkd4MzUwNEVFM1cxejFCIiwiZW1haWwiOiJhbHZhcm9WcXpkZWxldGVAdS10YWQuY29tIiwicm9sZSI6IlRFQUNIRVIiLCJpYXQiOjE3NDI5MTg1NzMsImV4cCI6MTc0MzAwNDk3M30.c7GzjZKXPOjUAAyI_un6_xenw8OSj0Y9YIyzlHiMSKM

###
GET http://localhost:3000/admin/deletionRequests
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6InpVaWM1RVY2a1cxS2xPSndlR2RMIiwiZW1haWwiOiJhZG1pbkB1LXRhZC5jb20iLCJyb2xlIjoiQURNSU4iLCJpYXQiOjE3NDMwMDkwMDcsImV4cCI6MTc0MzA5NTQwN30.Cp5x6_yGlovOGzCFVsdLaKp0i3Xg2-bFDWA2TPNkSvc