### register 
POST http://localhost:3000/register
Content-Type: application/json

{
  "email": "ALa@live.u-tad.com",
  "password": "SecurePass123!",
  "seedWord": "sash"
}

### login
POST http://localhost:3000/login
Content-Type: application/json

{
  "email": "ala@live.u-tad.com",
  "password": "SecurePass123!"
}

################################################
### estudiante entero 
GET http://localhost:3000/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImVGSmJtZzBJYzIzZnBsWlNBeUpTIiwiZW1haWwiOiJhbGFAbGl2ZS51LXRhZC5jb20iLCJyb2xlIjoiU1RVREVOVCIsInNlZWRXb3JkIjoic2FzaCIsImlhdCI6MTc0NTU5MTQxNiwiZXhwIjoxNzQ1Njc3ODE2fQ.GTejeExA_R4zWb1VM_f_XAtBQ4nhSS6cZ2Z4IBdMrq0

### metadata de un estudiante
GET http://localhost:3000/metadata
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IlBwZjlUSjFPV0ZiY1VZMXdqUHd0IiwiZW1haWwiOiJhbHZhcm9WcXpAbGl2ZS51LXRhZC5jb20iLCJyb2xlIjoiU1RVREVOVCIsImlhdCI6MTc0MDY1NTMwOSwiZXhwIjoxNzQwNzQxNzA5fQ.O8Jfj1MyXZjucTPj7zfmRf75V82hF2U6M9vetF6l05o

################################################
### actualizar metadata de un estudiante
PATCH http://localhost:3000/metadata
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImVGSmJtZzBJYzIzZnBsWlNBeUpTIiwiZW1haWwiOiJhbGFAbGl2ZS51LXRhZC5jb20iLCJyb2xlIjoiU1RVREVOVCIsInNlZWRXb3JkIjoic2FzaCIsImlhdCI6MTc0NTU5MTQxNiwiZXhwIjoxNzQ1Njc3ODE2fQ.GTejeExA_R4zWb1VM_f_XAtBQ4nhSS6cZ2Z4IBdMrq0

{
    "firstName": "Alvaro",
    "lastName": "Vazquez",
    "gender": "male",
    "degree": "INSO_DATA",
    "specialization": "Frontend Developer",
    "birthDate": "1985-08-20",
    "endDate": "2026-06-30",
    "programming_languages" : [
        { "name": "C", "level": "high" }
    ],
    "languages": [
        { "language": "English", "level": "C2" },
        { "language": "Spanish", "level": "C2" },
        { "language": "French", "level": "C2" }
    ],
    "certifications": [
        { "name": "AWS Certified Developer", "date": "2024-01-15", "institution": "Amazon" },
        { "name": "Microsoft Certified: Azure Developer Associate", "date": "2024-02-15", "institution": "Microsoft" },
        { "name": "Google Professional Data Engineer", "date": "2024-03-15", "institution": "Google" },
        { "name": "Oracle Certified Professional: Java SE 11 Developer", "date": "2024-04-15", "institution": "Oracle" }
    ],
    "workExperience": [
        { 
            "jobType": "Intern", 
            "startDate": "2023-06-01", 
            "endDate": "2023-12-31", 
            "company": "Nvidia", 
            "description": "AI Developer", 
            "responsibilities": "AI development tasks" 
        }
    ]
}

### testear
PATCH http://localhost:3000/metadata
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Ik1sR1l3Y1A5OGNvZ2NsSE54enprIiwiZW1haWwiOiJhbHZhcm9WcXpkZWxldGVAbGl2ZS51LXRhZC5jb20iLCJyb2xlIjoiU1RVREVOVCIsInNlZWRXb3JkIjoic2FzaCIsImlhdCI6MTc0MzM1NTc5OSwiZXhwIjoxNzQzNDQyMTk5fQ.qjaVmdXa1yfz3PwoPG4qBYEAip2TGuzxqcJuGwgpuBs

{
  "gender" :  "male"
}

###
PATCH http://localhost:3000/metadata
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Ik1sR1l3Y1A5OGNvZ2NsSE54enprIiwiZW1haWwiOiJhbHZhcm9WcXpkZWxldGVAbGl2ZS51LXRhZC5jb20iLCJyb2xlIjoiU1RVREVOVCIsInNlZWRXb3JkIjoic2FzaCIsImlhdCI6MTc0MzM1NTc5OSwiZXhwIjoxNzQzNDQyMTk5fQ.qjaVmdXa1yfz3PwoPG4qBYEAip2TGuzxqcJuGwgpuBs

{
  "languages": [
    { "_id": "25dc42f4-4604-4d8e-87e9-102dc2cec4e4", "language": "Spanish", "level": "C1" },
    {"language": "INDI", "level": "C1"}
  ]
}

###
PATCH http://localhost:3000/metadata
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Ik1sR1l3Y1A5OGNvZ2NsSE54enprIiwiZW1haWwiOiJhbHZhcm9WcXpkZWxldGVAbGl2ZS51LXRhZC5jb20iLCJyb2xlIjoiU1RVREVOVCIsInNlZWRXb3JkIjoic2FzaCIsImlhdCI6MTc0MzM1NTc5OSwiZXhwIjoxNzQzNDQyMTk5fQ.qjaVmdXa1yfz3PwoPG4qBYEAip2TGuzxqcJuGwgpuBs

{
  "workExperience": [
    {
      "_id": "590c1770-902c-4b0b-9595-f744ee24e5bd",
      "jobType": "Intern",
      "startDate": "2023-06-01",
      "endDate": "2023-12-31",
      "company": "Amazon",
      "description": "AI Developer Senior",
      "responsibilities": "AI"
    },
    {
      "jobType": "Intern",
      "startDate": "2023-06-01",
      "endDate": "2023-12-31",
      "company": "Google",
      "description": "AI Developer Junior",
      "responsibilities": "Basic AI"
    }
  ]
}

### 
PATCH http://localhost:3000/metadata
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Ik1sR1l3Y1A5OGNvZ2NsSE54enprIiwiZW1haWwiOiJhbHZhcm9WcXpkZWxldGVAbGl2ZS51LXRhZC5jb20iLCJyb2xlIjoiU1RVREVOVCIsInNlZWRXb3JkIjoic2FzaCIsImlhdCI6MTc0MzM1NTc5OSwiZXhwIjoxNzQzNDQyMTk5fQ.qjaVmdXa1yfz3PwoPG4qBYEAip2TGuzxqcJuGwgpuBs

{
  "programming_languages": [
    { "_id": "6b6392b7-4740-4a85-8925-0ae1492f9c25", "name": "C", "level": "high" },
    { "name": "Java", "level": "high" }
  ]
}

###
PATCH http://localhost:3000/metadata
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Ik1sR1l3Y1A5OGNvZ2NsSE54enprIiwiZW1haWwiOiJhbHZhcm9WcXpkZWxldGVAbGl2ZS51LXRhZC5jb20iLCJyb2xlIjoiU1RVREVOVCIsInNlZWRXb3JkIjoic2FzaCIsImlhdCI6MTc0MzM1NTc5OSwiZXhwIjoxNzQzNDQyMTk5fQ.qjaVmdXa1yfz3PwoPG4qBYEAip2TGuzxqcJuGwgpuBs

{
  "certifications": [
    { 
      "_id": "774a0173-26a2-454c-b65e-f079490c1a43",
      "name": "AWS Certified Developer",
      "date": "2024-01-15",
      "institution": "Amazon" 
    },
    { 
      "name": "Oracle Certified Professional: Java Developer",
      "date": "2024-04-20",
      "institution": "Oracle" 
    }
  ]
}

#############################################################
### Test para obtener un estudiante

###  Test para eliminar algun dato la metadata de un estudiante
DELETE http://localhost:3000/metadata
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Ik1sR1l3Y1A5OGNvZ2NsSE54enprIiwiZW1haWwiOiJhbHZhcm9WcXpkZWxldGVAbGl2ZS51LXRhZC5jb20iLCJyb2xlIjoiU1RVREVOVCIsInNlZWRXb3JkIjoic2FzaCIsImlhdCI6MTc0MzM1NTc5OSwiZXhwIjoxNzQzNDQyMTk5fQ.qjaVmdXa1yfz3PwoPG4qBYEAip2TGuzxqcJuGwgpuBs

{
  "programming_languages": [
    { "_id": "6b6392b7-4740-4a85-8925-0ae1492f9c25", "name": "C", "level": "high" }
  ]
}

###
DELETE http://localhost:3000/metadata
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Ik1sR1l3Y1A5OGNvZ2NsSE54enprIiwiZW1haWwiOiJhbHZhcm9WcXpkZWxldGVAbGl2ZS51LXRhZC5jb20iLCJyb2xlIjoiU1RVREVOVCIsInNlZWRXb3JkIjoic2FzaCIsImlhdCI6MTc0MzM1NTc5OSwiZXhwIjoxNzQzNDQyMTk5fQ.qjaVmdXa1yfz3PwoPG4qBYEAip2TGuzxqcJuGwgpuBs

{
  "languages": [
    { "_id": "cb9995cf-9817-44ef-9cc5-22fc50095fb2", "language": "Spanish", "level": "C1" }
  ]
}

###
DELETE http://localhost:3000/metadata
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Ik1sR1l3Y1A5OGNvZ2NsSE54enprIiwiZW1haWwiOiJhbHZhcm9WcXpkZWxldGVAbGl2ZS51LXRhZC5jb20iLCJyb2xlIjoiU1RVREVOVCIsInNlZWRXb3JkIjoic2FzaCIsImlhdCI6MTc0MzM1NTc5OSwiZXhwIjoxNzQzNDQyMTk5fQ.qjaVmdXa1yfz3PwoPG4qBYEAip2TGuzxqcJuGwgpuBs

{
  "certifications": [
    { 
      "_id":  "29ad254c-cd29-4dad-815b-03206ef2aab4",
      "name": "AWS Certified Developer",
      "date": "2024-01-15",
      "institution": "Amazon" 
    }
  ]
}

###
DELETE http://localhost:3000/metadata
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Ik1sR1l3Y1A5OGNvZ2NsSE54enprIiwiZW1haWwiOiJhbHZhcm9WcXpkZWxldGVAbGl2ZS51LXRhZC5jb20iLCJyb2xlIjoiU1RVREVOVCIsInNlZWRXb3JkIjoic2FzaCIsImlhdCI6MTc0MzM1NTc5OSwiZXhwIjoxNzQzNDQyMTk5fQ.qjaVmdXa1yfz3PwoPG4qBYEAip2TGuzxqcJuGwgpuBs

{
  "gender" :  "male"
}

### 
GET http://localhost:3000/updateHistory
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImVGSmJtZzBJYzIzZnBsWlNBeUpTIiwiZW1haWwiOiJhbGFAbGl2ZS51LXRhZC5jb20iLCJyb2xlIjoiU1RVREVOVCIsInNlZWRXb3JkIjoic2FzaCIsImlhdCI6MTc0NTU5MTQxNiwiZXhwIjoxNzQ1Njc3ODE2fQ.GTejeExA_R4zWb1VM_f_XAtBQ4nhSS6cZ2Z4IBdMrq0
