### Register Admin
POST http://localhost:3000/admin
Content-Type: application/json

### Login Admin
POST http://localhost:3000/login
Content-Type: application/json

{
  "email": "admin@u-tad.com",
  "password": "SecurePass@123"
}

### crear un roadmap (Admin)
POST http://localhost:3000/roadmaps/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6InpVaWM1RVY2a1cxS2xPSndlR2RMIiwiZW1haWwiOiJhZG1pbkB1LXRhZC5jb20iLCJyb2xlIjoiQURNSU4iLCJpYXQiOjE3NDIzODMxMjAsImV4cCI6MTc0MjQ2OTUyMH0.yskscKELiEL4WfH7tKeL9A-7JT-XX7316jZlzrDRo3U
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary

------WebKitFormBoundary
Content-Disposition: form-data; name="file"; filename="roadmapFrontend.json"
Content-Type: application/json

< ./roadmapFrontend.json
------WebKitFormBoundary--

### obtener todos los roadmaps (admin)
GET http://localhost:3000/roadmaps/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IkxxMlU3aEhtMkhuR1RSOFdLZlg5IiwiZW1haWwiOiJhbHZhcm8udmF6cXVlei4xNzE2QGdtYWlsLmNvbSIsInJvbGUiOiJBRE1JTiIsImlhdCI6MTc0MDM0MzIyMywiZXhwIjoxNzQwNDI5NjIzfQ.Ft3D9QzfJxAvrKL1cBBz0tZMYfd2IJiYYa5IZyCYtNw

### optener un roadmap por su nombre (admin)
GET http://localhost:3000/roadmaps/Artificial Intelligence
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IlNzV1F5N2JKR1BvVFFkbGg4RlRNIiwiZW1haWwiOiJhbHZhcm8udmF6cXVlei4xNzE2QGdtYWlsLmNvbSIsInJvbGUiOiJBRE1JTiIsImlhdCI6MTc0MTE5MDc4MywiZXhwIjoxNzQxMjc3MTgzfQ.3rJmK_dvN4l1UtlELNnXwnnjZHT70EGUYsS_Z_aLIaI

### login de un estudiante
POST http://localhost:3000/login
Content-Type: application/json

{
  "email": "alvaroVqz@live.u-tad.com",
  "password": "SecurePass123!"
}

### obtener un roadmap por su nombre (estudiante)
GET http://localhost:3000/roadmaps/student/Data Analyst
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Ijl1ZUhRdUhNOFVBRU0wUWV5QjB6IiwiZW1haWwiOiJhbHZhcm9WcXpAbGl2ZS51LXRhZC5jb20iLCJyb2xlIjoiU1RVREVOVCIsImlhdCI6MTc0MDMzNTE1MSwiZXhwIjoxNzQwNDIxNTUxfQ.bRsbhqybF0VbW7eTC-__MKbNoR7TB-FA9aJOZ4jRe4c

### actualizar un roadmap (Admin)
PATCH http://localhost:3000/roadmaps/Data Analyst
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IkxxMlU3aEhtMkhuR1RSOFdLZlg5IiwiZW1haWwiOiJhbHZhcm8udmF6cXVlei4xNzE2QGdtYWlsLmNvbSIsInJvbGUiOiJBRE1JTiIsImlhdCI6MTc0MDI2NTg5MSwiZXhwIjoxNzQwMzUyMjkxfQ.83R_ZkGetqjxHU5x8x4GaAp3SbBzReTO4xCGF_UqkHk
Content-Type: application/json

{
  "name": "Data Analyst updated",
}

### eliminar un roadmap (Admin)
DELETE http://localhost:3000/roadmaps/Data Analyst
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IkxxMlU3aEhtMkhuR1RSOFdLZlg5IiwiZW1haWwiOiJhbHZhcm8udmF6cXVlei4xNzE2QGdtYWlsLmNvbSIsInJvbGUiOiJBRE1JTiIsImlhdCI6MTc0MDI2NTg5MSwiZXhwIjoxNzQwMzUyMjkxfQ.83R_ZkGetqjxHU5x8x4GaAp3SbBzReTO4xCGF_UqkHk
